name: CI & Deploy

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-test:
    name: Lint, Test, Build (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Unit tests
        run: pnpm test

      - name: Build
        run: pnpm build
        env:
          SPOTIFY_CLIENT_ID: 927fda6918514f96903e828fcd6bb576
          MOCK: true

      - name: Create 404 fallback (SPA)
        if: ${{ matrix.node == '20' && github.event_name == 'push' }}
        run: cp dist/index.html dist/404.html

      - name: Upload dist artifact
        if: ${{ matrix.node == '20' && github.event_name == 'push' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          name: github-pages-20

  e2e:
    name: Playwright E2E (mock)
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile

      # Build the app for preview; MOCK must be defined at build time
      - name: Build (mock)
        run: pnpm build
        env:
          MOCK: true
          SPOTIFY_CLIENT_ID: 927fda6918514f96903e828fcd6bb576

      - name: Install browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: pnpm test:e2e